package com.example.ist412se_group1_efinance.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
// javax.persistence package imports
import javax.persistence.Entity;
import javax.persistence.Column;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.GenerationType;
import javax.persistence.GeneratedValue;
import javax.persistence.ManyToMany;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

@Entity // Create database entity
@Table(name = "customer") // Use customer table in MySQL
public class Customer implements Serializable{
    @Id // MySQL table ID field
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long cId; // Long ID is autogenerated
    @Column(name = "first_name")
    private String firstName;
    @Column(name = "last_name")
    private String lastName;
    @Column(name = "email")
    private String email;
    @Column(name="password")
    private String password;
    @Column(name="signup_date")
    private Date signUpDate = new Date();
    @Column(name="income")
    private Integer income; // Annual income
    @Column(name = "address")
    private String address;
    @Column(name = "city")
    private String city;
    @Column(name = "state")
    private String customerState;
    @Column(name = "zip")
    private String zip;
    @Column(name = "social")
    private String social;

    // Customers can have many loan apps. Loan apps can have many customers (cosigners)
    @ManyToMany(mappedBy="customers") // Mapped by customers variable in LoanApps
    @JsonIgnore
    public Set<LoanApp> loanApps = new HashSet<>();

    // Customers can have many loans. Loans can have many customers (cosigners)
    @ManyToMany(mappedBy="customers") // Mapped by customers variable in Loans
    @JsonIgnore
    public Set<Loan> loans = new HashSet<>();

    // Getters and Setters
    public long getcId() { return cId;}
    public void setcId(long Id) { this.cId = Id;}

    public String getFirstName() { return firstName;}
    public void setFirstName(String customerFirstName) { this.firstName = customerFirstName;}

    public String getLastName() { return lastName;}
    public void setLastName(String customerLastName) { this.lastName = customerLastName;}

    public String getEmail() { return email;}
    public void setEmail(String customerEmail) { this.email = customerEmail;}

    public String getPassword() { return password;}
    public void setPassword(String customerPassword) { this.password = customerPassword;}

    public Date getSignUpDate() { return signUpDate;}
    public void setSignUpDate(Date customerSignUpDate) { this.signUpDate = customerSignUpDate;}

    public Integer getIncome() { return income;}
    public void setIncome(Integer customerIncome) { this.income = customerIncome;}

    public String getAddress() { return address;}
    public void setAddress(String customerAddress) { this.address = customerAddress;}

    public String getCity() { return city;}
    public void setCity(String customerCity) { this.city = customerCity;}

    public String getCustomerState() { return customerState;}
    public void setCustomerState(String customerState) { this.customerState = customerState;}

    public String getZip() { return zip;}
    public void setZip(String customerZip) { this.zip = customerZip;}

    public String getSocial() { return social;}
    public void setSocial(String customerSocial) { this.social = customerSocial;}

    public Set<LoanApp> getLoanApps() { return loanApps;}
    public void setLoanApps(Set<LoanApp> loanApps) { this.loanApps = loanApps;}

    public Set<Loan> getLoans() { return loans;}
    public void setLoans(Set<Loan> loans) { this.loans = loans;}


    @Override
    public String toString() {
        String customerString = "";
        customerString += (
                "Customer ID: " + this.getcId() + "\n" +
                        "First Name: " + this.getFirstName() + "\n" +
                        "Last Name: " + this.getLastName() + "\n" +
                        "Email: " + this.getEmail() + "\n"  +
                        // "Password: " + this.getCustomerPassword() + "\n" +
                        "Hidden Password: " + this.hidePassword() + "\n" +
                        "Sign Up Date: " + this.getSignUpDate() + "\n" +
                        "Customer Income: " + this.getIncome() + "\n" +
                        "Address: " + this.getAddress() + "\n" +
                        "City: " + this.getCity() + "\n" +
                        "State: " + this.getCustomerState() + "\n" +
                        "Zip: " + this.getZip() + "\n" +
                        "Social: " + this.hideSocial(this.getSocial())
                );
        return customerString;
    }

    public String hideSocial(String customerSocial) { // Only displays last 4 digits of social
        String hiddenSocial = "";
        for(int i = 0; i < customerSocial.length(); i++) { // Only show last four digits (e.g., *****6789)
            if(i < customerSocial.length()-4) {
                hiddenSocial += "*";
            }
            else {
                hiddenSocial += customerSocial.charAt(i);
            }
        } // Convert to 123-45-**** format by inserting '-' after 3rd and 5th digits
        hiddenSocial = hiddenSocial.substring(0, 3) + "-" + hiddenSocial.substring(3, 5) + "-" +
                hiddenSocial.substring(5, 9);
        return hiddenSocial;
    }

    public String hidePassword() {
        String hiddenPassword = "";
        for(int i = 0; i < getPassword().length(); i++){
            hiddenPassword += "*";
        }
        return hiddenPassword;
    }
}
