package com.example.ist412se_group1_efinance.model;
// Persistence package/serializable imports
import javax.persistence.Entity;
import javax.persistence.Column;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.ManyToMany;
import javax.persistence.CascadeType;
import javax.persistence.JoinTable;
import javax.persistence.JoinColumn;
import java.io.Serializable;
// MISC util imports
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;

// Create/use database entity
@Entity 
// Create/use MySQL loan table
@Table(name="loan") 
public class Loan implements Serializable{
    private final int MONTHS_PER_YEAR = 12;

    @Id // MySQL table ID field
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    // Long ID is autogenerated for each loan
    private long lId; 
    // String used to get text from input type="date" in HTML
    @Column(name = "start_date")
    // Date loan funds will be disbursed to customer account
    private String startDate; 
    @Column(name = "principal")
    private Double principal;
    @Column(name = "apr")
    private Integer aPR;
    @Column(name = "term")
    // Integer can be null, int cannot
    private Integer term; 
    @Column(name = "monthly_interest_rate")
    private double monthlyInterestRate;
    @Column(name = "monthly_payment")
    private double monthlyPayment;
    @Column(name = "balance")
    private Double balance;
    @Column(name = "personnel_id")
    private long personnelId;

    // Customers can have many loans
    // Loans can have many customers: signer, cosigner(s)
    @ManyToMany(cascade = CascadeType.MERGE) 
    @JoinTable(name = "loan_customer",
            // Loan ID
            joinColumns = {@JoinColumn(name = "loan_id")}, 
            // Customer ID   
            inverseJoinColumns = {@JoinColumn(name = "customer_id")}) 
    public Set<Customer> customers = new HashSet<>();

    // Format doubles with commas and decimal point
    public String getDoubleWithTwoDecimals(Double doubleValue) {
        return ("").format("%,.2f" , doubleValue);} 

    public void calculateLoanValues(){
        // Amortized loan balance equation: 
        // https://www.thebalance.com/loan-payment-calculations-315564
        // Check balance value with Credit Karma calculator:
        // https://www.creditkarma.com/calculators/amortization
        monthlyInterestRate = getAPR() / 100.0 / MONTHS_PER_YEAR;
        monthlyPayment = principal /((Math.pow(1 + monthlyInterestRate, term) - 1)/
                (monthlyInterestRate *Math.pow(1 + monthlyInterestRate, term)));
        // Round monthly payment and multiply it by loan term to calculate loan balance
        balance = 
            Math.round((Math.round(monthlyPayment *100.0)/100.0) * term * 100.0)/100.0;
        System.out.println("Loan Term: " + term);
        System.out.println("Loan Monthly Interest Rate: " + monthlyInterestRate);
        System.out.println("Loan Monthly Payment: " + monthlyPayment);
        System.out.println("Loan Balance: " + balance);
    }

    @Override
    public String toString() {
        String loanString = "";
        loanString += (
                "Loan/Application ID: " + this.getlId() + "\n" +
                        "Loan Start Date: " + this.getStartDate() +
                        "Loan Principal: " + this.getPrincipal() + "\n"  +
                        "Loan APR: " + this.getAPR() + "\n" +
                        "Loan Term: " + this.getTerm() + "\n" +
                        "Loan Monthly Interest Rate: " + 
                        this.getMonthlyInterestRate() + "\n" +
                        "Loan Monthly Payment: " + this.getMonthlyPayment() + "\n" +
                        "Loan Balance: " + this.getBalance() + "\n" +
                        "Customer Set: " + this.getCustomers());
        return loanString;
    }
    
    // Getters and Setters
    public long getPersonnelId() { return personnelId;}
    public void setPersonnelId(long loanPersonnelId) { this.personnelId = loanPersonnelId;}
    
    public long getlId() { return lId;}
    public void setlId(long loanId) { this.lId = loanId;}

    public String getStartDate() { return startDate;}
    public void setStartDate(String loanStartDate) { this.startDate = loanStartDate;}

    public Double getPrincipal() { return principal;}
    public void setPrincipal(Double loanPrincipal) { this.principal = loanPrincipal;}

    public Integer getAPR() { return aPR;}
    public void setAPR(Integer loanAPR) { this.aPR = loanAPR;}

    public Integer getTerm() { return term;}
    public void setTerm(Integer loanTerm) { this.term = loanTerm;}

    public Double getBalance() { return balance;}
    public void setBalance(Double loanBalance) { this.balance = loanBalance;}

    public Set<Customer> getCustomers() { return customers;}
    public void setCustomers(Set<Customer> customers) { this.customers = customers;}

    public void setPrimaryCustomer(Customer customer) { customers(0) = customer;}
    public Customer getPrimaryCustomer() {
        ArrayList<Customer> customerArrayList = new ArrayList<>(getCustomers());
        return customerArrayList.get(0);}

    public Double getMonthlyInterestRate() { return monthlyInterestRate;}
    public void setMonthlyInterestRate(Double loanMonthlyInterestRate) { this.monthlyInterestRate =
            loanMonthlyInterestRate;}

    public Double getMonthlyPayment() { return monthlyPayment;}
    public void setMonthlyPayment(Double loanMonthlyPayment) { this.monthlyPayment = loanMonthlyPayment;}
}
